"""description

Revision ID: 998d5efb1fa2
Revises: b8c0d2e4f6a8
Create Date: 2026-06-11 22:01:05.756760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '998d5efb1fa2'
down_revision: Union[str, Sequence[str], None] = 'b8c0d2e4f6a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_pair'), table_name='chat_messages')
    op.create_index(op.f('ix_inspection_k3l_tindak_lanjut_history_id'), 'inspection_k3l_tindak_lanjut_history', ['id'], unique=False)
    op.create_index(op.f('ix_inspection_k3l_validasi_history_id'), 'inspection_k3l_validasi_history', ['id'], unique=False)
    op.drop_index(op.f('ix_notifications_user_unread'), table_name='notifications')
    op.drop_index(op.f('ix_case_incidents_id'), table_name='report_case_incidents')
    op.create_index(op.f('ix_report_case_incidents_id'), 'report_case_incidents', ['id'], unique=False)
    op.drop_index(op.f('ix_report_comments_target'), table_name='report_comments')
    op.drop_column('users', 'business_unit')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(), server_default=sa.text("'user'::character varying"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('business_unit', sa.VARCHAR(), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_report_comments_target'), 'report_comments', ['report_type', 'report_id'], unique=False)
    op.drop_index(op.f('ix_report_case_incidents_id'), table_name='report_case_incidents')
    op.create_index(op.f('ix_case_incidents_id'), 'report_case_incidents', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_unread'), 'notifications', ['user_id', 'is_read'], unique=False)
    op.drop_index(op.f('ix_inspection_k3l_validasi_history_id'), table_name='inspection_k3l_validasi_history')
    op.drop_index(op.f('ix_inspection_k3l_tindak_lanjut_history_id'), table_name='inspection_k3l_tindak_lanjut_history')
    op.create_index(op.f('ix_chat_messages_pair'), 'chat_messages', ['sender_id', 'recipient_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
